vim:fileencoding=utf-8:foldmethod=marker


font_family JetBrainsMono Nerd Font
disable_ligatures always
font_size 16.0

# Padding settings (in pixels)
window_padding_width 12

background_type transparent

# Set smooth text rendering
text_antialiasing yes
subpixel_rendering yes

# Scrollback lines
scrollback_lines 10000

# Enable bold font
bold_font yes

# Custom font for bold text
bold_font_family JetBrainsMono Nerd Font

cursor_trail 1
cursor_trail_decay 0.15 0.3
cursor_trail_start_threshold 2
mouse_hide_wait 2.0
include themes/noctalia.conf
